[luna] class1-1
ktb-23/python-study pull request #7
Opened 2024-07-22 16:22 UTC by MoiJiyeon

<img width="815" alt="스크린샷 2024-07-23 오전 1 23 09" src="https://github.com/user-attachments/assets/f71c69d0-22d6-4aa8-8f87-4a30d82dd228">

2024-07-23 08:17 UTC, HanMulBit requested changes
지금 py파일들 경로를 luna/class1-1/문제번호.py로 파일 경로만 바꿔주시면 될 것 같습니다!

2024-07-24 02:28 UTC, MoiJiyeon commented
파일 경로 수정했습니다!

2024-07-24 02:33 UTC, MoiJiyeon reviewed
해당 내용 수정했습니다.

2024-07-24 15:44 UTC, timepresent95 approved these changes
첫 스터디 수고 많으셨습니다!!

2024-07-24 15:44 UTC, timepresent95 commented on luna/class1-1/#4 1008.py
> +print(A/B)
```suggestion
a, b = map(int, input().split())
print(a / b)
```

변수 이름을 대문자로 사용하지 않는것을 추천드립니다
- 보편적으로 대문자는 상수를 의미합니다. (예: API_KEY)

map(int, input().split())을 사용하여 형변환을 한번에 할 수 있습니다. 
- 해당 방식을 통해 보다 파이썬스럽게 코드를 사용할 수 있습니다.

2024-07-24 15:44 UTC, timepresent95 commented on luna/class1-1/#4 25083.py
> +print("""      |""")
```suggestion
print(r"""         ,r'"7
r`-_   ,'  ,/
 \. ". L_r'
   `~\/
      |
      |""")
```

위와 같은 문법을 통해 한번에 출력이 가능합니다.
print(r"""<출력 값>""") 에서 r의 의미는 escape 문자를 무시한다는 뜻입니다.
해당 내용도 함께 검색해보시면 다양한 출력 방법을 공부하시는데 도움 될것 같습니다.

2024-07-25 02:10 UTC, HanMulBit approved these changes

2024-07-25 02:25 UTC, MoiJiyeon commented on luna/class1-1/#4 1008.py
> +print(A/B)
문제에서  '첫 줄에 A와 B가 주어진다'라고 되어있을 때에도
답안 코드를 작성할 때 A와 B 대신 a b 등으로 사용해야 하나요?

2024-07-25 02:27 UTC, MoiJiyeon commented on luna/class1-1/#4 25083.py
> +print("""      |""")
몇 번 하다가 뭐가 잘 안 되길래 한 줄마다 해야하는 줄 알았어요.
제가 코드를 잘못 작성했었나봅니다!
안 그래도 aiden이랑 sean 코드 보고 알았어요.
이렇게 한 번 더 성장합니다!

2024-07-25 02:31 UTC, timepresent95 commented on luna/class1-1/#4 1008.py
> +print(A/B)
변수 이름을 소문자로 사용하는것은 필수적으로 따라야하는 규칙이 아니라
원하시는대로 해도상관 없습니다.
다만 보편적인 방식을 사용하는게 추후 협업시에도 서로가 작성한 코드를 읽기 쉬워서 추천 드린 내용입니다.
보다 자세한 보편적 규칙을 알고싶으시다면 [구글 파이썬 스타일 가이드](https://yosseulsin-job.github.io/Google-Python-Style-Guide-kor/#s3.1) 읽어보시는거 추천드리고
(조금 양이 많아 시간 나실때 천천히 읽어보시길 추천드립니다.)
변수 이름과 관련된 스타일 규칙은 [여기](https://yosseulsin-job.github.io/Google-Python-Style-Guide-kor/#s3.16) 있습니다.

2024-07-25 02:38 UTC, MoiJiyeon commented on luna/class1-1/#4 1008.py
> +print(A/B)
고맙습니다~

2024-07-25 02:43 UTC, merged